### PR TITLE
Remove deprecated logic, modernise project

### PR DESCRIPTION
**Pull request by marcusirgens**
This issue tracks a more thorough rewrite of this code, which has turned a bit stale. This includes the fixes in mwitkow/grpc-proxy#51, which replaces the framing logic with the more idiomatic `anypb.Any` type, while also removing the deprecated `grpc.CustomCodec()` calls.

As far as I can tell, this rewrite is 100% backwards compatible, but I'm eager to perform some more tests with some more complex protos.

This PR includes
- Some more tests of the testing server
- A more flexible testing server
- Rewrite to go modules
- Some sugar methods and sane defaults for ease of use (`proxy.NewProxy`)

I do suggest tagging this as 0.2 if this is merged at some point.

Feedback and contributions are greatly appreciated.

### CODE REVIEW

**Review by johanbrandhorst — APPROVED** [review]
LGTM

**Comment by DennisMao** [comment]
.editconfig  can be reomved or igored.

**Review by johanbrandhorst — APPROVED** [review]

**Comment by johanbrandhorst** [comment]
(I don't have the permission to merge this).

**Comment by tmc** [comment]
@mwitkow would you be open to opening up maintainers on this codebase?

**Comment by bwplotka** [comment]
Thanks @johanbrandhorst and others! Let's get this rolling 💪🏽 

@tmc I think we should add more maintainers and I can try to arrange that (I can't add people), if anyone wants to help. Feel free to shoot me a message to bwplotka @ gmail.com

@johanbrandhorst do you have time to help too? 🙈

**Comment by bwplotka** [comment]
Great work BTW @marcusirgens  - this was definitely needed.

**Comment by johanbrandhorst** [comment]
I would love to help if I can :)

**Comment by marcusirgens** [comment]
I'm open to contributing to this project. 👍🏻

**Comment by gedw99** [comment]
I plan to get http/3 WebTransport working with this, and would like to help.

**Comment by fabregas** [comment]
@marcusirgens  you can't unmarshal any binary protobuf message to anypb.Any. This is **wrong** assumption.

Any message declaration:

message Any {
  string type_url = 1;
  bytes value = 2;
}

So in some cases we will receive error "grpc: failed to unmarshal the received message string field contains invalid UTF-8" bcs it can't unmarshal type_url string.

**Pull request merged**
