### PR TITLE
Use Empty rather than Any for message processing

### LINKED ISSUE #61: Fields marked as `repeated` are truncated
While proxying messages that contain `repeated` fields, the values are truncated to only their last value. This happens both on incoming messages and the outgoing response. I created a simple test service that exhibits this behavior. Given a proto looks like:
```
service Greeter {
  rpc SayHelloAgain (HelloRequest) returns (RepeatedHelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

message RepeatedHelloReply {
  repeated string message = 1;
}
```
When I hit the gRPC service directly, I get an array of strings back:
```
$ grpcurl -plaintext -d '{"name": "Joe"}' localhost:50051 Greeter/SayHelloAgain
{
  "message": [
    "1: Hello Joe",
    "2: Hello Joe",
    "3: Hello Joe",
    "4: Hello Joe",
    "5: Hello Joe"
  ]
}
```

However making that same call via the proxy I get a truncated response:
```
grpcurl -plaintext -d '{"name": "Joe"}' localhost:50052 Greeter/SayHelloAgain
{
  "message": [
    "5: Hello Joe"
  ]
}
```

I've attached my example service that exhibits the behavior. The basic gRPC server runs on `:50051` while the proxy runs on `50052`. Use `make run` to start the service, and `make test` to hit the service to reproduce the issue.
[grpc-proxy-test.zip](https://github.com/mwitkow/grpc-proxy/files/8771971/grpc-proxy-test.zip)

Thanks in advanced for your assistance!

### PR DESCRIPTION
**Pull request by adamthesax**
This fixes #61. This is also based off of #57

### CODE REVIEW

**Comment by vito** [comment]
@mwitkow Sorry to nag, but any chance this could be merged? :slightly_smiling_face: I ran into this issue as well.

**Comment by floatingstatic** [comment]
Hi, I would also like to see if we can bump looking into merging this. For me this fixes both https://github.com/mwitkow/grpc-proxy/issues/59 and https://github.com/mwitkow/grpc-proxy/issues/61

Thanks!

**Comment by tzasacky** [comment]
Bump, I ran into this issue as well.

**Comment by dlakshma** [comment]
> This fixes #61. This is also based off of #57
https://github.com/mwitkow/grpc-proxy/issues/59
Wanted to check the reason this PR request is not merged. With the suggested fix "grpc: failed to unmarshal the received message string field contains invalid UTF-8" is not seen when querying the gRPC server using the grpc-proxy

**Comment by realguoqiang** [comment]
Thanks for the fix which saves my life! Though this hasn't been merged yet.

**Comment by andremarianiello** [comment]
I need this change too! Thanks!

**Comment by mwitkow** [comment]
Hi folks, sorry for not looking into this earlier. I rarely read my github messages.

**Pull request merged**
